# This is a basic workflow to help you get started with Actions
name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      

# Permissions needed for creating releases
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build and Release APK"
  releases:
    name: Build and Release APK
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Get version from pubspec.yaml
        id: version
        run: |
          version=$(grep 'version:' pubspec.yaml | cut -c10-)
          echo "version=$version" >> "$GITHUB_OUTPUT"
        working-directory: xcore_mobile

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get packages
        run: flutter pub get
        working-directory: xcore_mobile
        
      - name: Decode Keystore
        working-directory: xcore_mobile/android
        run: echo "${{ secrets.KEY_JKS }}" | base64 -d > release-keystore.jks

      - name: Create key.properties
        working-directory: xcore_mobile/android
        run: |
          cat <<EOF > key.properties
          storePassword=${{ secrets.KEY_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=release
          storeFile=release-keystore.jks
          EOF
          
      - name: Build APK
        run: flutter build apk --release
        working-directory: xcore_mobile

      - name: Cleanup signing files
        if: always()
        working-directory: xcore_mobile/android
        run: |
          rm -f release-keystore.jks key.properties


      - name: Get current date
        id: date
        run: |
          date_output=$(TZ='Asia/Jakarta' date +'%A %d-%m-%Y %T WIB')
          echo "date=$date_output" >> "$GITHUB_OUTPUT"

      - name: Generate unique tag
        id: tag
        run: |
          echo "tag=v${{ steps.version.outputs.version }}-$(date +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifacts: "xcore_mobile/build/app/outputs/flutter-apk/*.apk"
          body: "Published at ${{ steps.date.outputs.date }}"
          name: "v${{ steps.version.outputs.version }} - ${{ steps.date.outputs.date }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.tag.outputs.tag }}
